<?php
  require("includes/header.php");
?>

    <main id="main__index">
      <div id="div__slider">
        <figure id="slider" class="slider">
          <img id="slide">
          <button id="slider-previous" type="button" name="button"><i class="fa fa-chevron-circle-left" aria-hidden="true"></i></button>
          <button id="slider-next" type="button" name="button"><i class="fa fa-chevron-circle-right" aria-hidden="true"></i></button>
        </figure>
      </div>
      <article>
        <img class="gallyImg left__float" src="img/gally.jpg" alt="Gally">
        <p>Bienvenue sur le site regroupant les oeuvres (BD, manga, comics) considérés comme indispensables, choisis par les utilisateurs du forum.</p>
      </article>
      <div class="clearfix"></div>
    </main>

<?php
  require("includes/footer.php");
?>
